// -------------------- Icons (PNG) --------------------
// ✅ あなたのPNGファイル名に合わせてここを編集するだけでOK。
// 例：/ICONS にPNGを置いた想定（index.html と同階層に ICONS フォルダ）
const ICONS = {
  "白熊": "./ICONS/bear.png",
  "ずっとも": "./ICONS/seat_heart.png",
  "誕生日ボーイ&ガール": "./ICONS/cake.png",
  "水チェイサー": "./ICONS/water.png",
  "じゃんけん王": "./ICONS/crown_hand.png",
  "共通点探し": "./ICONS/venn.png",
  "指差し": "./ICONS/point.png",
  "独裁": "./ICONS/spotlight.png",
  "右隣": "./ICONS/arrow_right.png",
  "左隣": "./ICONS/arrow_left.png",
  "向かい": "./ICONS/facing.png",
  "偶数席": "./ICONS/arrow_right.png",
  "奇数席": "./ICONS/arrow_left.png",
  "最年長": "./ICONS/crown.png",
  "最年少": "./ICONS/baby.png",
  "メデゥーサ": "./ICONS/medusa_eye.png",
  "遅刻": "./ICONS/spotlight.png",
  "人気者": "./ICONS/phone_heart.png",
  "キス": "./ICONS/seat_heart.png",
  "ラッパー": "./ICONS/mic.png",
  "乾杯": "./ICONS/clink.png",
  "究極の選択": "./ICONS/choice.png",
  "倍々ファイト": "./ICONS/crown_hand.png",
  "お残しチェック": "./ICONS/glass_level.png",
  "ロック画面": "./ICONS/lockscreen.png",
  "電池残量（少ない）": "./ICONS/battery_low.png",
  "電池残量（多い）": "./ICONS/battery_full.png",
  "一斉に乾杯": "./ICONS/clink.png",
  "連想ゲーム": "./ICONS/venn.png",
  "セーフティ": "./ICONS/check.png",
  "バリア": "./ICONS/shield.png",
  "ガードマン": "./ICONS/guard.png",
  "なにした": "./ICONS/point.png",
  "二択ジャッジ": "./ICONS/choice.png",
  "多数決": "./ICONS/venn.png",
  "ワンワード": "./ICONS/phone_heart.png",
  "3・2・1": "./ICONS/point.png",

  default: "./ICONS/target.png",
};
